const fs = require("fs");

module.exports = async ({ github, context }) => {
  const sarifFiles = [
    "semgrep.sarif",
    "trivy-results.sarif",
    "checkov.sarif",
    "bicep.sarif",
    "snyk.sarif",
  ];
  let checkRows = [];
  let failCount = 0;

  for (const file of sarifFiles) {
    if (fs.existsSync(file)) {
      try {
        const data = fs.readFileSync(file, "utf8");
        const sarif = JSON.parse(data);
        const runs = sarif.runs || [];
        let count = 0;
        runs.forEach((run) => {
          count += (run.results || []).length;
        });

        const status = count > 0 ? "❌ Failed" : "✅ Passed";
        checkRows.push(
          `| ${file.replace(".sarif", "")} | ${status} | ${count} issues |`,
        );
        if (count > 0) failCount++;
      } catch (e) {
        checkRows.push(`| ${file} | ⚠️ Error | Could not parse |`);
      }
    } else {
      checkRows.push(`| ${file} | ⚪ Skipped | N/A |`);
    }
  }

  const overallStatus =
    failCount > 0 ? "❌ Security Checks Failed" : "✅ Security Checks Passed";

  const body = `
  ## 🛡️ FortressCI Security Summary
  
  **Status**: ${overallStatus}
  
  | Scanner | Status | Findings |
  | :--- | :--- | :--- |
  ${checkRows.join("\n")}
  
  ---
  
  Generated by [FortressCI](https://github.com/mackeh/FortressCI) 🏰
  `;

  // Post comment
  if (context.issue.number) {
    await github.rest.issues.createComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: context.issue.number,
      body: body,
    });
  }
};
